env: "local"
grpc:
  port: 8000
kafka:
  host: "kafka"
  port: 29092
  topic: "analyzer"
  detection_topic: "detection"
detection:
  host: "localhost"
  port: 8001
limiter:
  max_requests: 5
  per: 1s