version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mq

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
    depends_on:
      - zookeeper
    networks:
      - mq

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - mq

  producer:
    build:
      context: ./producer
      dockerfile: ./Dockerfile
    container_name: producer
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - mq

  consumer:
    build:
      context: ./consumer
      dockerfile: ./Dockerfile
    container_name: consumer
    restart: unless-stopped
    ports:
      - "8002:8000"
    networks:
      - mq

networks:
  mq:
      driver: bridge