version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - waf-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - waf-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - waf-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - waf-network

  analyser:
    build:
      context: ./analyser
      dockerfile: ./Dockerfile
    container_name: analyser
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - waf-network

  detection:
    build:
      context: ./detection
      dockerfile: ./Dockerfile
    container_name: detection
    restart: unless-stopped
    depends_on:
      - kafka
      - redis
    networks:
      - waf-network

  waf:
    build:
      context: ./waf
      dockerfile: ./Dockerfile
    container_name: waf
    restart: unless-stopped
    depends_on:
      - kafka
      - analyser
      - detection
    networks:
      - waf-network

networks:
  waf-network:
      driver: bridge