name: Deploy on push

# Runs tests on any push in main
on:
  push:
    branches:
      - 'main'

jobs:
  lint-waf:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: waf
          args: --config=../.golangci.yml
  lint-analyzer:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: analyzer
          args: --config=../.golangci.yml
  lint-detection:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: detection
          args: --config=../.golangci.yml

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: |
          sleep 10
          docker ps -a
          docker network ls
      - run: make test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test, lint-waf, lint-analyzer, lint-detection]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd waf
          make update